server:
  port: 8084

spring:
  application:
    name: netfliz-admin

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  main:
    allow-bean-definition-overriding: true

  graphql:
    cors:
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      max-age: 1800s

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        search:
          default:
            directory_provider: local-heap

  servlet:
    multipart:
      max-file-size: 600MB
      max-request-size: 600MB


application:
  security:
    jwt:
      expiration: 600000
      refresh-token:
        expiration: 604800000
